safe:        false
auto:        false
server:      false
server_port: 4000
baseurl:    /
url: http://localhost:4000
exclude: ["img-orig"]

source:      .
destination: ../../build/manual
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date
