safe:        false
baseurl:    /
url: http://localhost:4000
exclude: ["img-orig"]

source:      .
destination: ../../build/manual
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date
